/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoA3;

import Classe.Agua;

/**
 *
 * @author clebe
 */
public class Alimentacao extends javax.swing.JFrame {

    /**
     * Creates new form ListarAlunos
     */
    public Alimentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        jLabel18.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabel18.setText("Refeição 2: Almoço");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(644, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ganho de massa magra:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 240, 21);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("-Aveia cozida com leite ou água");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 180, 15);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-Frutas como banana ou morangos");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 200, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-Peito de frango grelhado ou assado");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 200, 210, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("-Arroz integral ou batata doce");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 230, 190, 20);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-Legumes cozidos ou salada verde");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 320, 210, 16);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("-Salmão grelhado ou assado");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(20, 260, 170, 17);

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("-Quinoa ou lentilhas");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 290, 130, 16);

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("-Vegetais cozidos no vapor ou salada");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 350, 220, 16);

        jLabel20.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel20.setText("-Peito de frango grelhado ou peixe");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(823, 934, 188, 16);

        jLabel21.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel21.setText("-Salada verde com vegetais e uma colher de sopa de azeite de oliva");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(823, 972, 372, 16);

        jLabel22.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabel22.setText("Refeição 3: Jantar");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(823, 1028, 131, 16);

        jLabel12.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel12.setText("-Sopa de legumes caseira ou salada grande com ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(823, 1067, 276, 16);

        jLabel25.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel25.setText("proteína magra (frango grelhado, atum em água)");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(823, 1090, 268, 16);

        jLabel24.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel24.setText("-Uma porção de vegetais cozidos no vapor");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(823, 1112, 233, 16);

        jLabel26.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel26.setText("-Uma porção de vegetais cozidos no vapor");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(823, 956, 233, 16);

        jLabel27.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabel27.setText("Refeição 2: Almoço");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(823, 907, 133, 16);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ALIMENTAÇÃO ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 30, 138, 30);

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 430, 10, 20);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/Alimentacao.JPG"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(0, -10, 320, 500);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ALIMENTAÇÃO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 30, 160, 30);

        jLabel15.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("2");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(480, 430, 10, 20);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Receitas para emagrecer:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 100, 240, 21);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("-Salada simples");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 150, 140, 15);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("-Salada de atum");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 160, 130, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("-Salada com frutas");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(340, 200, 100, 10);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("-Salada de grão-de-bico");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(340, 210, 160, 40);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("-Sopa detox de legumes");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(340, 240, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/Alimentacao.JPG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 0, 320, 480);

        jLabel31.setText("jLabel31");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(340, 250, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
