/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoA3;

import Classe.Agua;
import javax.swing.JOptionPane;

/**
 *
 * @author clebe
 */
public class Exercicios extends javax.swing.JFrame {

    /**
     * Creates new form Apagar
     */
    public Exercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(615, 375));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Segunda-feira (peito):");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 200, 14);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTA DE EXERCÍCIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 198, 33);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("- Supino inclinado (4 x 8-12)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 200, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("- Supino reto (4 x 8-12)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 120, 210, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("- Crossover na polia baixa (3 x 8-12)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 140, 220, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("- Crossover na polia alta (3 x 8-12)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 160, 200, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Terça-feira (quadriceps e panturrilha):");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 290, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("- Agachamento livre (4 x 8-12)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 230, 200, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("- Cadeira extensora (4 x 8-12)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 250, 230, 14);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("- Leg Press (3 x 8-12)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 270, 170, 14);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("- Gêmeos no smith (5 x 10-15)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 290, 290, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quinta-feira (costas):");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 70, 170, 14);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("- Puxada alta com barra (4 x 8-12)");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 104, 220, 10);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("- Puxada alta com triângulo (4 x 8-12) ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 120, 210, 14);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("- Remada unilateral (4 x 8-12)");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 140, 210, 14);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("- Pulldown (3 x 8-12)");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 160, 180, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Sexta-feira (Braço):");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 200, 180, 14);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("- Rosca martelo (4 x 8-12)");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(340, 230, 180, 14);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("- Rosca alternada (4 x 8-12)");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(340, 250, 200, 14);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("- Tríceps polia (4 x 8-12)");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(340, 270, 200, 14);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("- Tríceps frânces (4 x 8-12)");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(340, 290, 200, 14);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("- Elevação lateral (6 x 8)");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(340, 310, 190, 14);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/exercicios.jpeg"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 600, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
