package projetoA3;


import Classe.Agua;
import javax.swing.JOptionPane;

public class Hidratacao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroNota
     */
    public Hidratacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelNota2 = new javax.swing.JLabel();
        inputAgua = new javax.swing.JTextField();
        buttonCadastrar = new javax.swing.JButton();
        labelMedia = new javax.swing.JLabel();
        labelmediaa = new javax.swing.JLabel();
        labelmediaaa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(644, 500));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hidratação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 30, 194, 48);

        labelNome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        labelNome.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(labelNome);
        labelNome.setBounds(23, 1276, 82, 0);

        labelNota2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNota2.setForeground(new java.awt.Color(255, 255, 255));
        labelNota2.setText("Peso");
        getContentPane().add(labelNota2);
        labelNota2.setBounds(300, 140, 100, 32);

        inputAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAguaActionPerformed(evt);
            }
        });
        getContentPane().add(inputAgua);
        inputAgua.setBounds(290, 230, 80, 30);

        buttonCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadastrar);
        buttonCadastrar.setBounds(260, 360, 140, 41);
        getContentPane().add(labelMedia);
        labelMedia.setBounds(599, 1282, 92, 0);

        labelmediaa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(labelmediaa);
        labelmediaa.setBounds(495, 1400, 196, 28);

        labelmediaaa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelmediaaa.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelmediaaa);
        labelmediaaa.setBounds(260, 290, 250, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/hidratacao.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 869);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed

        Agua aluno = new Agua();
        
       
        String nota1 = inputAgua.getText();
      
        
        
        if(
                nota1.equalsIgnoreCase("")) 
                {
        
                JOptionPane.showMessageDialog(null,
                        "Digite todos os valores");
        
        }else{
              
                aluno.setNota1(Double.parseDouble(nota1));
               
                
                aluno.inserir();
                
             labelmediaaa.setText("Meta diária: " + aluno.getMedia() + " Litros.");
                
                
        }
        
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void inputAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAguaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hidratacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hidratacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hidratacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hidratacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hidratacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JTextField inputAgua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelMedia;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNota2;
    private javax.swing.JLabel labelmediaa;
    private javax.swing.JLabel labelmediaaa;
    // End of variables declaration//GEN-END:variables
}
