package projetoA3;


import javax.swing.JOptionPane;
import Classe.Usuario;
import projetoA3.Menu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author clebe
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        inputUsuario = new javax.swing.JTextField();
        inputPasswordFieldSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/Login.jpg"))); // NOI18N
        jLabel1.setInheritsPopupMenu(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -140, 810, 740);

        buttonLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.setOpaque(false);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogin);
        buttonLogin.setBounds(310, 290, 180, 40);

        inputUsuario.setToolTipText("");
        inputUsuario.setBorder(null);
        getContentPane().add(inputUsuario);
        inputUsuario.setBounds(310, 210, 180, 20);

        inputPasswordFieldSenha.setBorder(null);
        getContentPane().add(inputPasswordFieldSenha);
        inputPasswordFieldSenha.setBounds(310, 250, 180, 20);

        setSize(new java.awt.Dimension(817, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed


        String senha = inputPasswordFieldSenha.getText();
        String usuario = inputUsuario.getText();
        String email = inputUsuario.getText();       
        Usuario u = new Usuario();
        u.setSenha(senha);
        u.setUsuario(usuario);
        
        if(u.validarUsuario(usuario, senha)){
            Menu i = new Menu();
            i.setVisible(true);
        
        }else{
            JOptionPane.showMessageDialog(null, 
                    "tente novamente");    
        }        
                
                
                
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPasswordField inputPasswordFieldSenha;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
